package market.engine.theme

import org.jetbrains.compose.resources.StringResource

interface Strings {
    val continueLabel: StringResource
    val selectCategory: StringResource
    val profileTitleBottom: StringResource
    val menuTitle: StringResource
    val homeTitle: StringResource
    val searchTitle: StringResource
    val createNewOfferTitle: StringResource
    val createNewOrderTitle: StringResource
    val searchUsersSearch: StringResource
    val notificationTitle: StringResource
    val messageTitle: StringResource
    val subcategories: StringResource
    val topOffersTitle: StringResource
    val proposalTitle: StringResource
    val profileTitle: StringResource
    val actionClose: StringResource
    val allPromoOffersBtn : StringResource
    val clear: StringResource
    val logoutTitle: StringResource
    val searchHistory: StringResource
    val loginTitle: StringResource
    val registerTitle: StringResource
    val favoritesTitle: StringResource
    val basketTitle: StringResource
    val top100Title: StringResource
    val top100Subtitle: StringResource
    val helpTitle: StringResource
    val helpSubtitle: StringResource
    val contactUsTitle: StringResource
    val contactUsSubtitle: StringResource
    val settingsProfileTitle: StringResource
    val settingsProfileSubtitle: StringResource
    val reviewsTitle: StringResource
    val reviewsSubtitle: StringResource
    val settingsTitleApp : StringResource
    val settingsSubtitleApp : StringResource
    val aboutUsTitle : StringResource
    val aboutUsSubtitle : StringResource
    val selectSearchTitle : StringResource
    val searchUserStringChoice : StringResource
    val searchUserFinishedStringChoice : StringResource
    val categoryCollection : StringResource
    val parameters : StringResource
    val categoryVintage : StringResource
    val categoryElectronic : StringResource
    val categoryOther : StringResource
    val categoryBeauty : StringResource
    val categoryBook : StringResource
    val categoryMusic : StringResource
    val categoryPhone : StringResource
    val categorySport : StringResource
    val categoryMusicBooksFilms : StringResource
    val categoryElectronic2 : StringResource
    val categoryFashion : StringResource
    val categoryRetro : StringResource
    val resetLabel : StringResource
    val categoryArt : StringResource
    val categoryCoin : StringResource
    val categoryBanknotes : StringResource
    val categoryMarks : StringResource
    val categoryMedals : StringResource
    val categoryPorcelain : StringResource
    val categoryBooks : StringResource
    val categoryNotebooks : StringResource
    val categoryAppliances : StringResource
    val categoryMain : StringResource
    val homeFixAuction : StringResource
    val homeManyOffers : StringResource
    val verifySellers : StringResource
    val everyDeyDiscount : StringResource
    val freeBilling : StringResource
    val currencySign : StringResource
    val currencyCode : StringResource
    val homeTopCategory : StringResource
    val noInternetTitle : StringResource
    val noInternetSubtitle : StringResource
    val refreshButton : StringResource
    val numberOfItems : StringResource
    val numberOfBids : StringResource
    val oopsTitle : StringResource
    val notFoundListingTitle : StringResource
    val categoryEnter : StringResource
    val allOffers : StringResource
    val filter : StringResource
    val sort : StringResource
    val ordinaryAuction : StringResource
    val buyNow : StringResource
    val saleTypeParameterName : StringResource
    val discountPrice : StringResource
    val discountPriceParameterName : StringResource
    val saleTypeNameFromOne : StringResource
    val specialFilters : StringResource
    val offerWithSafeDealParameterName : StringResource
    val offerWithVideoParameterName : StringResource
    val regionParameterName : StringResource
    val chooseAction : StringResource
    val actionAcceptFilters : StringResource
    val priceParameterName : StringResource
    val fromAboutParameterName : StringResource
    val toAboutParameterName : StringResource
    val timeParameterName : StringResource
    val offersFor : StringResource
    val newOffersWithoutRelistedFor : StringResource
    val endingWith : StringResource
    val oneHour : StringResource
    val twoHour : StringResource
    val threeHour : StringResource
    val fourHour : StringResource
    val fiveHour : StringResource
    val twelveHour : StringResource
    val _24Hour : StringResource
    val _2Days : StringResource
    val _3Days : StringResource
    val _4Days : StringResource
    val _5Days : StringResource
    val _6Days : StringResource
    val _7Days : StringResource
    val timeToEnd : StringResource
    val sortModeIncreasing : StringResource
    val sortModeDecreasing : StringResource
    val titleParameterName : StringResource
    val sortModeIncreasingAlphabetically : StringResource
    val sortModeDecreasingAlphabetically : StringResource
    val offersGroupStartTSTile : StringResource
    val sortModeOldestFirst : StringResource
    val sortModeNewestFirst : StringResource
    val enterCaptcha : StringResource
    val promptEmail : StringResource
    val promptPassword : StringResource
    val forgotPassword : StringResource
    val enterLogin : StringResource
    val registration : StringResource
    val errorLogin : StringResource
    val operationSuccess : StringResource
    val operationFailed : StringResource
    val checkForLogoutTitle : StringResource
    val closeWindow : StringResource
    val loginParameterName : StringResource
    val offersLabel : StringResource
    val promoEndLabel : StringResource
    val noBuyer : StringResource
    val noBids : StringResource
    val blitzAuction : StringResource
    val offerSessionInactiveLabel : StringResource
    val deleteSelectOffers : StringResource
    val activeFilterOffers : StringResource
    val inactiveFilterOffers : StringResource
    val withSalesFilterOffers : StringResource
    val withoutSalesFilterOffers : StringResource
    val noTradeTypeFilterOffers : StringResource
    val auctionWithBuyNow : StringResource
    val simpleAuction : StringResource
    val offersState : StringResource
    val myFavoritesTitle : StringResource
    val mySubscribedTitle : StringResource
    val offersCategoryParameterName : StringResource
    val offerIdParameterName : StringResource
    val offerNameParameterName : StringResource
    val sellerLoginParameterName : StringResource
    val myBidsTitle : StringResource
    val myBidsSubTitle : StringResource
    val proposalPriceTitle : StringResource
    val proposalPriceSubTitle : StringResource
    val myPurchasesTitle : StringResource
    val myPurchasesSubTitle : StringResource
    val myOffersTitle : StringResource
    val myOffersSubTitle : StringResource
    val mySalesTitle : StringResource
    val mySalesSubTitle : StringResource
    val messageSubTitle : StringResource
    val myProfileTitle : StringResource
    val myProfileSubTitle : StringResource
    val profileSettingsTitle : StringResource
    val profileSettingsSubTitle : StringResource
    val myBalanceTitle : StringResource
    val myBalanceSubTitle : StringResource
    val ratingParameterName : StringResource
    val vacationLabel : StringResource
    val vacationTitle : StringResource
    val vacationHeaderSettingsLabel : StringResource
    val activeTab : StringResource
    val inactiveTab : StringResource
    val futureTab : StringResource
    val buyerParameterName : StringResource
    val winnerParameterName : StringResource
    val copyOfferId : StringResource
    val copyOrderId : StringResource
    val messageAboutError : StringResource
    val deleteSelectedLot : StringResource
    val warningDeleteSubscription : StringResource
    val acceptAction : StringResource
    val actionConfirm : StringResource
    val idCopied : StringResource
    val defaultOfferTitle : StringResource
    val lastViewedOffers : StringResource
    val ourChoice : StringResource
    val description : StringResource
    val tempPhotoLabel : StringResource
    val shareOffer : StringResource
    val addToCalendar : StringResource
    val quantityParameterName : StringResource
    val fromParameterName : StringResource
    val boughtParameterName : StringResource
    val viewsParams : StringResource
    val actionsOffersParameterName : StringResource
    val operationsParameterName : StringResource
    val actionParameterName : StringResource
    val promoActionsParameterName : StringResource
    val activatePromoParameterName : StringResource
    val currentPriceParameterName : StringResource
    val yourMaxBidParameterName : StringResource
    val actionAddBid : StringResource
    val buyNowPriceParameterName : StringResource
    val additionalDescriptionsParameterName : StringResource
    val standardDescriptionParameterName : StringResource
    val editedStandardDescriptionParameterName : StringResource
    val saleLabel : StringResource
    val actionAskSellerLabel : StringResource
    val actionProposalPriceLabel : StringResource
    val whoPayForDeliveryLabel : StringResource
    val antiSniperEnabledLabel : StringResource
    val bidsMadeLabel : StringResource
    val leadingBidsNowLabel : StringResource
    val yourBidsFirstLabel : StringResource
    val yourBidLabel : StringResource
    val daysLabel : StringResource
    val dayLabel : StringResource
    val hourLabel : StringResource
    val hoursLabel : StringResource
    val minutesLabel : StringResource
    val secondsLabel : StringResource
    val offerSessionFutureLabel : StringResource
    val offerSessionCompletedLabel : StringResource
    val beforeGraduationLabel : StringResource
    val aboutMeLabel : StringResource
    val publicVacationMyLabel : StringResource
    val publicVacationHeaderLabel : StringResource
    val publicVacationHeaderEndLabel : StringResource
    val publicVacationCommentLabel : StringResource
    val publicBlockUserLabel : StringResource
    val blackListUserLabel : StringResource
    val whiteListUserLabel : StringResource
    val sellerLabel : StringResource
    val paymentAndDeliveryLabel : StringResource
    val dealTypeLabel : StringResource
    val paymentMethodLabel : StringResource
    val deliveryMethodLabel : StringResource
    val withinCountry : StringResource
    val withinCity : StringResource
    val withinWorld : StringResource
    val commentLabel : StringResource
    val parametersLabel : StringResource
    val bidsLabel : StringResource
    val bidsUserLabel : StringResource
    val dateParameterName : StringResource
    val rebidLabel : StringResource
    val emptyFavoritesLabel : StringResource
    val simpleNotFoundLabel : StringResource
    val positiveFeedbackLabel : StringResource
    val subscriptionsLabel : StringResource
    val subscribersLabel : StringResource
    val createdUserLabel : StringResource
    val lastActiveUserLabel : StringResource
    val showAnswerLabel : StringResource
    val hideAnswerLabel : StringResource
    val orderLabel : StringResource
    val positiveFilterParams : StringResource
    val negativeFilterParams : StringResource
    val neutralFilterParams : StringResource
    val allFilterParams : StringResource
    val allFeedbackToUserLabel : StringResource
    val fromBuyerLabel : StringResource
    val fromSellerLabel : StringResource
    val fromUsersLabel : StringResource
    val emptyAboutMeLabel : StringResource
    val notFoundFeedbackLabel : StringResource
    val editOfferLabel : StringResource
    val actionSaveLabel : StringResource
    val sellOfferLabel : StringResource
    val changeCategory : StringResource
    val inCategoryLabel : StringResource
    val charactersLeftLabel : StringResource
    val sizeLabel : StringResource
    val fileNotFound : StringResource
    val fileTooLarge : StringResource
    val failureUploadPhoto : StringResource
    val actionAddPhoto : StringResource
    val photoLabel : StringResource
    val saleTypeLabel : StringResource
    val deliveryCityParameterLabel : StringResource
    val deliveryCountryParameterLabel : StringResource
    val deliveryWorldParameterLabel : StringResource
    val offerStartNowLabel : StringResource
    val offerStartInactiveLabel : StringResource
    val offerStartInFutureLabel : StringResource
    val selectTimeActiveLabel : StringResource
    val actionChangeLabel :  StringResource
    val descriptionPlaceholderLabel : StringResource
    val createSimilarOfferLabel : StringResource
    val congratulationsLabel : StringResource
    val congratulationsCreateOfferInFutureLabel : StringResource
    val actionClearBasket : StringResource
    val yourBasketTitle : StringResource
    val manyOffersLabel : StringResource
    val exManyOffersLabel : StringResource
    val oneOfferLabel : StringResource
    val cardIsEmptyLabel : StringResource
    val startShoppingLabel : StringResource
    val offerAddedToBasketLabel : StringResource
    val deleteSelectedOffersFromBasket : StringResource
    val priceOfOneOfferLabel : StringResource
    val totalLabel : StringResource
    val actionBuy : StringResource
    val inStockLabel : StringResource
    val warningDeleteSelectedOfferFromBasket : StringResource
    val warningDeleteOfferBasket : StringResource
    val defaultCardLabel : StringResource
    val addressCardsTitle : StringResource
    val addNewDeliveryCard : StringResource
    val actionDelete : StringResource
    val editCardLabel : StringResource
    val saveDataLabel : StringResource
    val countryDefault : StringResource
    val actionCancel : StringResource
    val actionComplete : StringResource
    val chooseAmountLabel : StringResource
    val tabAllLabel : StringResource
    val tabInWorkLabel : StringResource
    val tabArchiveLabel : StringResource
    val sortCreationDate : StringResource
    val searchOfferNameParameterName: StringResource
    val orderIdParameterName: StringResource
    val buyerLoginParameterName: StringResource
    val buyerIdParameterName: StringResource
    val sellerIdParameterName: StringResource
    val dateCreatedLabel : StringResource
    val totalCostLabel : StringResource
    val feeOrderLabel : StringResource
    val feeWasRefund : StringResource
    val offersParticipantsLabel : StringResource
    val costLabel : StringResource
    val myFeedbacksLabel : StringResource
    val toMeFeedbacksLabel : StringResource
    val tagsLabel : StringResource
    val trackIdLabel : StringResource
    val infoDeliveryLabel : StringResource
    val writeSellerLabel : StringResource
    val writeBuyerLabel : StringResource
    val fromAboutTimeLabel : StringResource
    val toAboutTimeLabel : StringResource
    val commentForYouLabel : StringResource
    val setReportBuyersLabel : StringResource
    val setReportSellersLabel : StringResource
    val setTrackIdLabel : StringResource
    val feedbackTypePositiveLabel : StringResource
    val feedbackTypeNeutralLabel : StringResource
    val feedbackTypeNegativeLabel : StringResource
    val messageLabel : StringResource
    val defaultCommentReport : StringResource
    val createConversationLabel : StringResource
    val aboutOrderLabel : StringResource
    val aboutOfferLabel : StringResource
    val dialogPhone : StringResource
    val dialogZip : StringResource
    val dialogCity : StringResource
    val dialogCountry : StringResource
    val dialogComment : StringResource
    val dialogFio : StringResource
    val dialogAddress : StringResource
    val additionalDeliveryInfo : StringResource
    val placeBetOnTheAmount : StringResource
    val acceptAddBidsAction : StringResource
    val yourselfBidsLabel : StringResource
    val userLoginParameterName : StringResource
    val userIdParameterName : StringResource
    val offerOrderIdParameterName : StringResource
    val conversationsLabel : StringResource
    val selectedItemsLabel : StringResource
    val deleteConversationLabel : StringResource
    val todayLabel : StringResource
    val notReadMessagesLabel : StringResource
    val yourMessagesLabel : StringResource
    val deleteDialogLabel : StringResource
    val textCopied: StringResource
    val actionCopy: StringResource
    val profileSellerSettingsLabel : StringResource
    val profileAdditionalSettingsLabel : StringResource
    val profileGlobalSettingsLabel : StringResource
    val genderParameterName : StringResource
    val sexMaleParameterName : StringResource
    val sexFemaleParameterName : StringResource
    val notSetParameterName : StringResource
    val phoneParameterName : StringResource
    val pageAboutMeParameterName : StringResource
    val dialogChooseActionLabel : StringResource
    val deleteAvatarLabel : StringResource
    val setLoginTitle : StringResource
    val setNewLoginTitle : StringResource
    val yourCurrentLogin : StringResource
    val editEmailTitle : StringResource
    val checkOutEmailToast : StringResource
    val htmlVerifyLabel : StringResource
    val submitSmsLabel : StringResource
    val acceptChangesLabel : StringResource
    val verificationSmsLabel : StringResource
    val registrationDisclaimer : StringResource
    val registrationSuccessLabel : StringResource
    val goBackLabel : StringResource
    val contactUsHeaderLabel : StringResource
    val actionSend : StringResource
    val notificationSettingsLabel : StringResource
    val actionGoToNotificationsSettingsLabel : StringResource
    val settingsThemeLabel : StringResource
    val themeLightLabel : StringResource
    val themeDarkLabel : StringResource
    val emptySubscriptionsLabel : StringResource
    val createNewSubscriptionTitle : StringResource
    val subscriptionOnLabel : StringResource
    val subscriptionOffLabel : StringResource
    val editLabel : StringResource
    val allProposalLabel : StringResource
    val needResponseProposalLabel : StringResource
    val subtitleProposalCountLabel : StringResource
    val subtitleOfferCountLabel : StringResource
    val countsSign : StringResource
    val notFoundProposalsLabel : StringResource
    val forLabel : StringResource
    val proposalAcceptLabel : StringResource
    val withCommentProposalLabel : StringResource
    val proposalRejectLabel : StringResource
    val sellerProposalRejectLabel : StringResource
    val proposalLeftUnansweredLabel : StringResource
    val leftUnansweredLabel : StringResource
    val yourProposeLabel : StringResource
    val sellerProposalAcceptLabel : StringResource
    val sellerProposeLabel : StringResource
    val buyerWaitYourAnswer : StringResource
    val buyerProposeLabel : StringResource
    val yourProposeWaitAnswer : StringResource
    val sellerWaitYourAnswer : StringResource
    val waitAnswerSeller : StringResource
    val waitAnswerBuyer : StringResource
    val mayAnswerTo : StringResource
    val leftLabel : StringResource
    val historyLabel : StringResource
    val warningDeleteHistory : StringResource
    val currentStateOfferLabel : StringResource
    val snapshotLabel : StringResource
    val messageToBuyersLabel : StringResource
    val headerMessageToBuyersLabel : StringResource
    val settingsBiddingStepsLabel : StringResource
    val settingsAutoFeedbacksLabel : StringResource
    val settingsWatermarkLabel : StringResource
    val sellerSettingsTitle : StringResource
    val addressesSettingsTitle : StringResource
    val blackListSettingsTitle : StringResource
    val outgoingAddressLabel : StringResource
    val outgoingAddressHeaderLabel : StringResource
    val settingsBlackListSellersLabel : StringResource
    val settingsBlackListBuyersLabel : StringResource
    val settingsWhiteListBuyersLabel : StringResource
    val settingsBlockRatingLabel : StringResource
    val autoFeedbackTitle : StringResource
    val autoFeedbackSubtitle : StringResource
    val autoFeedbackAfterExceededTimeTitle : StringResource
    val autoFeedbackAfterExceededTimeSubtitle : StringResource
    val watermarkHeaderLabel : StringResource
    val headerDeliveryCardLabel : StringResource
}
